-- Migration: Create manual_invoices table for Neela's Sarees
CREATE TABLE IF NOT EXISTS `manual_invoices` (
  `id` VARCHAR(36) NOT NULL,
  `invoice_number` VARCHAR(100) NOT NULL UNIQUE,
  `invoice_date` VARCHAR(50) NOT NULL,
  `due_date` VARCHAR(50) DEFAULT NULL,
  `customer_name` VARCHAR(191) NOT NULL,
  `customer_email` VARCHAR(191) DEFAULT NULL,
  `customer_phone` VARCHAR(50) DEFAULT NULL,
  `customer_address` TEXT DEFAULT NULL,
  `customer_gstin` VARCHAR(50) DEFAULT NULL,
  `payment_method` VARCHAR(50) DEFAULT 'Cash',
  `transaction_id` VARCHAR(100) DEFAULT NULL,
  `payment_status` VARCHAR(50) DEFAULT 'Paid',
  `seller_location` VARCHAR(255) DEFAULT NULL,
  `seller_landmark` VARCHAR(255) DEFAULT NULL,
  `seller_phone` VARCHAR(50) DEFAULT NULL,
  `seller_gstin` VARCHAR(50) DEFAULT NULL,
  `bank_account_holder` VARCHAR(191) DEFAULT NULL,
  `bank_name` VARCHAR(191) DEFAULT NULL,
  `bank_account_number` VARCHAR(100) DEFAULT NULL,
  `bank_ifsc` VARCHAR(50) DEFAULT NULL,
  `bank_branch` VARCHAR(191) DEFAULT NULL,
  `items` LONGTEXT NOT NULL,
  `subtotal` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `tax_rate` DECIMAL(5, 2) NOT NULL DEFAULT 5.00,
  `tax_amount` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `discount_amount` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `shipping_charge` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `grand_total` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `notes` TEXT DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `idx_invoice_number` (`invoice_number`),
  INDEX `idx_customer_name` (`customer_name`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
